Optional tag enforcement
schubergphilis/terraform-aws-mcaf-landing-zone pull request #152
Opened 2022-12-07 11:49 UTC by sbkg0002

* Introduce `var.split_aws_tag_policy`. When enabled, splits a Tag Policy in a separate policy per tag_key.
* Add possibility to enforce tag policy per tag, for [supporting services](https://docs.aws.amazon.com/organizations/latest/userguide/orgs_manage_policies_supported-resources-enforcement.html).
* Add `all` reference to substitute all [supporting services](https://docs.aws.amazon.com/organizations/latest/userguide/orgs_manage_policies_supported-resources-enforcement.html)

2022-12-07 11:55 UTC, stromp commented on modules/tag-policy-assignment/output.tf
> +output "policy_id" {
if it outputs a dict, I guess the name should also be plural

2022-12-07 11:58 UTC, stromp commented on modules/tag-policy-assignment/variables.tf
> +  description = "Map of tags"
because the module is also about tags it might be good to be explicit that this is about the tags on the resource

2022-12-07 15:10 UTC, stromp submitted a review, later dismissed
LGTM

2022-12-08 15:59 UTC, marwinbaumannsbp commented on modules/tag-policy-assignment/versions.tf
> +terraform {
since this is a submodule i would say you can remove the version constraint all together

2022-12-13 08:08 UTC, shoekstra requested changes

2022-12-13 08:08 UTC, shoekstra commented on UPGRADING.md
> +Be aware that all Tag policies are recreated since they are now created per tag_key in stead of per ou.
```suggestion
Be aware that all tag policies will be recreated since they are now created per tag policy instead of per OU.
```

2022-12-13 09:02 UTC, merged