feature: Refactor AWS Security Hub configuration
schubergphilis/terraform-aws-mcaf-landing-zone pull request #185
Opened 2023-07-24 10:35 UTC by marwinbaumannsbp

# Behaviour 
 
Before this PR `auto-enable default standards` was enabled by default. This PR modifies this behaviour to disabled by default (controlled by `var.security_hub.auto_enable_default_standards`) since the default standards are not updated regularly enough. At time of writing only the `AWS Foundational Security Best Practices v1.0.0 standard` and the `CIS AWS Foundations Benchmark v1.2.0` are enabled by [by default](https://docs.aws.amazon.com/securityhub/latest/userguide/securityhub-standards-enable-disable.html) while this module enables the following standards:

- `AAS Foundational Security Best Practices v1.0.0`
- `CIS AWS Foundations Benchmark v1.4.0`
- `PCI DSS v3.2.1`

The enabling of the standards in all member account is now controlled via [mcaf-account-baseline](https://github.com/schubergphilis/terraform-aws-mcaf-account-baseline).

# Variables

The following variables have been replaced by a new variable `aws_security_hub`:

- `aws_security_hub_product_arns` -> `aws_security_hub.product_arns`
- `security_hub_standards_arns` -> `aws_security_hub.override_standards_arns`
- `security_hub_create_cis_metric_filters` -> `aws_security_hub.create_cis_metric_filters`

2023-07-24 12:03 UTC, stefanwb approved these changes
LGTM

2023-07-25 07:35 UTC, marwinbaumannsbp commented on README.md
> +- `AAS Foundational Security Best Practices v1.0.0`
```suggestion
- `AWS Foundational Security Best Practices v1.0.0`
```

2023-07-25 09:02 UTC, shoekstra requested changes

2023-07-25 09:02 UTC, shoekstra commented on README.md
> +This module supports enabling Security Hub at the organization level which means that all new accounts that are created in, or added to, the organization are added as member accounts to the `audit` a
```suggestion
This module supports enabling Security Hub at an organization level, meaning all accounts that are created in or enrolled to the organization will be added as member accounts to the `audit` account Security Hub delegated administrator.
```

2023-07-25 09:04 UTC, shoekstra approved these changes

2023-07-25 09:04 UTC, merged