Adds support for custom AWS Okta Groups
schubergphilis/terraform-aws-mcaf-landing-zone pull request #2
Opened 2020-11-02 12:25 UTC by fgoncalves-io

2020-11-02 18:39 UTC, marwinbaumannsbp approved these changes

2020-11-02 19:14 UTC, shoekstra commented
I'd like to put this on hold until [support for SSO permission sets](https://github.com/hashicorp/terraform-provider-aws/pull/15322) has been merged until the AWS provider.

While it's just okta groups it doesn't make sense to be part of this module; if it's Okta groups together with permission sets then it makes sense.

2020-11-03 08:07 UTC, marwinbaumannsbp commented
On the one hand I agree with you that its better to add support for Okta groups i.c.w. SSO permission sets so the full solution is implemented, but on the other hand not merging this makes the migration of the Geldmaat inception harder. If we are not going to merge this, are we then going to document that the creation of Okta groups is manual for now and remove this from the state? Maybe we should have a short call about this today! :-)

2020-11-03 09:50 UTC, fgoncalves-io commented
We have decided to remove the Okta Groups from the module and manage them separately until we can implement the full solution including SSO permission set assignments.

2020-11-03 10:12 UTC, shoekstra commented on variables.tf
> +  description = "List of Okta Group Ids that should have the Amazon Web Services Okta app assigned"
```suggestion
  description = "List of Okta group IDs that should be assigned the AWS SSO Okta app"
```

2020-11-03 10:13 UTC, shoekstra requested changes
Minor fix required 🙂

2020-11-03 10:15 UTC, shoekstra approved these changes

2020-11-03 10:31 UTC, merged

2020-11-03 19:02 UTC, burck1 commented
Hi @fgoncalves-io, @shoekstra, @marwinbaumannsbp. 

In the interest of getting the AWS SSO resources merged, please go give a thumbs up to [15808](https://github.com/hashicorp/terraform-provider-aws/pull/)

We've completed most of the work for supporting the [AWS SSO](https://docs.aws.amazon.com/singlesignon/latest/APIReference/welcome.html) and [AWS SSO Identity Store](https://docs.aws.amazon.com/singlesignon/latest/IdentityStoreAPIReference/welcome.html) resources and datasources in Terraform. The [15322](https://github.com/hashicorp/terraform-provider-aws/pull/) [WIP] PR encompasses all of that work. But, the contribution guide for the repo recommends submitting small pull requests with the minimum required resources, so we've submitted [15808](https://github.com/hashicorp/terraform-provider-aws/pull/) as our initial PR with just `data.aws_sso_instance`, `data.aws_sso_permission_set`, and `aws_sso_permission_set`. Once that's merged, we will submit PRs for all of the other resources and data sources since they depend on that initial PR.